### ISSUE TITLE
device doesn't reboot after reset

### ISSUE THREAD

**Issue by bertmelis** [JoaoLopesF/RemoteDebug#10]
While connected through telnet I can rest the device. It is not rebooting however.

Serial output shows a WDT reset (which is the last message and then nothing...)

**Comment by bertmelis** [comment]
ok, it's a generale issue not related to this lib.

**Comment by JoaoLopesF** [comment]
Hi,

I have seen in several articles on the internet about the reset of the ESP8266
And several say that a major cause is about power supply and
indicate capacitors to reduce the resets.

I use an electrolytic capacitor 1000uf (470uf or more) and ceramic 0.1uf between the VIN and GND pins of the ESP8266.

I hope it helps

Regards

Joao
