### ISSUE TITLE
Change debug serial

### ISSUE THREAD

**Issue by merlokk** [JoaoLopesF/RemoteDebug#13]
Can you add some functionality to change debug serial port?

**Comment by JoaoLopesF** [comment]
Hi,

Why do you need this? please give me more information.

Regards

Joao

**Comment by merlokk** [comment]
Sometimes Serial connected to sensor or controlled device and only way to send logs is send them via Serial1 or SoftwareSerial....

**Comment by JoaoLopesF** [comment]
Hi,

The purpose this library is the telnet, not serial.
Why you not use telnet to see the logs ?

Regards,

Joao
