### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by bospre** [JoaoLopesF/RemoteDebug#16]
Hello,
unfortunately the library does not run with the ESP32. Will there be any adjustments?
Boris

**Comment by JoaoLopesF** [comment]
Hi, Its runs in ESP32, I will update the library now
Regards
Joao

**Comment by JoaoLopesF** [comment]
HI, I update it for the ESP32.
Please give me feedback

Regards

Joao

**Comment by bospre** [comment]
Good Morning,
ok, thank you.
I will test, but need some time.

**Comment by bospre** [comment]
Hello,
I have been testing and it seems to work.
Unfortunately my ESP32 triggers a "brownout" when attached via USB to the computer.
Sometimes it boots, most times not.
So I could not get the mDNS working.
For my project I need SPIFFS and cannot upload data to the SPIFFS.
I now ordered two more ESP32, to see if this is an issue with my ESP32. And I will wait until full SPIFFS integration is finished.
