### ISSUE TITLE
Update to Usage section

### ISSUE THREAD

**Issue by JSCSJSCS** [JoaoLopesF/RemoteDebug#19]
It may be useful to other readers if you added this to the "Usage" section of the readme"

`RemoteDebug Debug;`

The "basic" example was not very basic to me, so I followed the Usage section thinking that would be bare minimum, but instead I got errors "Debug not declared in this scope". 

I like the implementation. Simple to use.
I want to give a big thumbs up to the suggestion in #18. That would be a big help too.

**Comment by JoaoLopesF** [comment]
Hi, I will do it.
Thanks a lot.
Joao
