### ISSUE TITLE
Question: Can you only get debug message in Loop()?

### ISSUE THREAD

**Issue by JSCSJSCS** [JoaoLopesF/RemoteDebug#20]
I would like to be able to get some debug message in the void setup() funtion and even before. Is there any way to do that? I looks like you have to wait for Debug.handle() to run in the void loop() function before any Debug.printf() lines will get executed.

So happy to at least get some Loop() debug with OTA updates.

**Comment by JoaoLopesF** [comment]
HI, The debug in setup I recommend only serial, because no have time to telnet client connect.
Is for it only remote debug in another places and not in setup

Is clear ?

Regards

Joao
