### ISSUE TITLE
Redirect Serial output

### ISSUE THREAD

**Issue by dicastro** [JoaoLopesF/RemoteDebug#23]
I like your idea of remote debugging over telnet. But I see one problem, which is that most of existing libraries use `Serial` class to trace things. And this traces will not be seen in telnet connection.

Wouln't be possible to redirect `Serial` output to telnet? I mean implementing something to override default logic. In this way existing libraries traces could be debugged over telnet

**Comment by JoaoLopesF** [comment]
Hi Di castro,

I not do it in this library. 
Only method to do it is changing original Serial code in plataform, but I not recomend it.

Regards

Joao
