### ISSUE TITLE
Way of setting Telnet port

### ISSUE THREAD

**Issue by PjotrekSE** [JoaoLopesF/RemoteDebug#24]
Hi there, and thanx for this nice addition. Worx like a charm.
For reasons of obfuscating, I want to set the Telnet port to something other than 23. I designed a solution for this, see included files. I also changed the word 'setted' into 'set' in several places, hope you don't mind.
Keep up the good work!
PjotrekSE

[RemoteDebug.cpp.txt](https://github.com/JoaoLopesF/RemoteDebug/files/1919294/RemoteDebug.cpp.txt)
[RemoteDebug.h.txt](https://github.com/JoaoLopesF/RemoteDebug/files/1919295/RemoteDebug.h.txt)

**Comment by JoaoLopesF** [comment]
Hi, thanks for your suggestion,
I will do this soon

Regards,

Joao

**Comment by JoaoLopesF** [comment]
Hi,
Your code is very good, I like use of pointer to WiFiServer .
I apreciate your suggestion, but how this is used once time in project, is more simple, modify the port in RemoteDebug.h.
In the next version, I can modify it for project:

#define TELNET_PORT 1000
#include "RemoteDebug.h"

It is a very good suggestion to increase security

I change the "setted"s, it will in next version
I modify the initial comments in RemoteDebug.h, as exists in your version

Thanks a lot

**Comment by JoaoLopesF** [comment]
In the next version, I can modify for project:

#define TELNET_PORT 1000
#include "RemoteDebug.h"

Regards
