### ISSUE TITLE
Compile Error in Platform.io IDE

### ISSUE THREAD

**Issue by stritti** [JoaoLopesF/RemoteDebug#31]
I have updated to current version 1.4 getting now compile errors. E.g.
```
.piolibdeps\RemoteDebug_ID1266/RemoteDebug.h:180:39: error: expected primary-expression before '...' token
#define rdebug(fmt, ...) rdebugA(fmt, ...)
^
```
See also travis-build: https://travis-ci.org/stritti/smart-swimming-pool

**Comment by stritti** [comment]
I think  line https://github.com/JoaoLopesF/RemoteDebug/blob/eb80cf8fc5c5b8b792a09a577ca3ec9b342f63a4/RemoteDebug.h#L180

should be changed to:

```#define rdebug(fmt, ...) rdebugA(fmt, ##__VA_ARGS__)```

That works for me.

**Comment by JoaoLopesF** [comment]
Hi, @stritti 

Yes, Your solution is   ##correct.
I just updating the library to 1.5.2
Thanks a lot

**Comment by stritti** [comment]
Maybe there is missing an update for Platform.io? I can see your update in the repro, but the Travis build still fails. It shows that it uses version 1.4.0 but I have not defined special version in platform.ini: 
https://github.com/stritti/smart-swimming-pool/blob/master/Pool-Controller/platformio.ini

**Comment by JoaoLopesF** [comment]
Hi @stritti ,

Please verify now, I update library.json

**Comment by stritti** [comment]
now it works, thank you very much @JoaoLopesF !
