### ISSUE TITLE
RemoteDebug_Advanced example, little error

### ISSUE THREAD

**Issue by g-zajac** [JoaoLopesF/RemoteDebug#4]
processCmdRemoteDebug doest work properly, in line 288
if (Debug.getLastCommand() = "bench1") {
should be "==" instead of "="?

also Debug.ative, ative is typo with active?
The library is amazing! Thank you

**Comment by pieman64** [comment]
@grzegorzshub well spotted. Does anyone know how to disable Debug once it's been enabled with Debug.begin()?

**Comment by JoaoLopesF** [comment]
HI,

Sorry for the delay. I dont see the gmail messages.

grzegorzshub:
Bug fixed, Thanks a lot

pieman64: 
You can use stop() method. 

Regards

Joao
