### ISSUE TITLE
set debug level to OFF again with "o" ?

### ISSUE THREAD

**Issue by ozett** [JoaoLopesF/RemoteDebug#6]
you have letters for the specific debug-level.
but is there also an "o" or null/0-Zero to set the debug level to "off" again?

or back to the "default" debug-level? what is this?

would be fantastic ... 😄 

thanks, very helpful tool!

<img width="446" alt="redebug" src="https://cloud.githubusercontent.com/assets/5937811/20702539/8a446a56-b618-11e6-94ff-5c88651f9ff5.png">

**Comment by JoaoLopesF** [comment]
Hi,

Sorry for the delay

Please try the lastest version

Regards 

Joao
