### ISSUE TITLE
Can i have CarriageReturn/line-feed for debug output (like on serial monitor)

### ISSUE THREAD

**Issue by ozett** [JoaoLopesF/RemoteDebug#7]
if i use no "\n" new-line,
or if i use "\n" new line, 

my debug output scrolls somehow.
can i get formatted output (one line after the other), like on serial monitor?

thanks,
tozett

(see ->, it scrolls  within the lines...)
<img width="400" alt="debug2" src="https://cloud.githubusercontent.com/assets/5937811/20703058/89969e74-b61a-11e6-8b74-9363efde7828.png">

**Comment by pieman64** [comment]
Same question from me.
At the moment I am adding a Debug.println(); after each line but this seems a big of a hack.

**Comment by JoaoLopesF** [comment]
Hi,

Sorry for the delay.

A question: Is Windows telnet client ?
A version 1.0.0 supports Windows client (\r\n).

Regards

Joao
