### ISSUE TITLE
Free heap decreases after connect/disconnect

### ISSUE THREAD

**Issue by bertmelis** [JoaoLopesF/RemoteDebug#9]
I did a small test with a sample sketch:
connected to telnet: OK
quit connection: OK
connected again: OK, small decrease in free heap
quit connection OK
tried to connect again but "connection refused"

I could post my sketch if needed.

**Comment by bertmelis** [comment]
Oeps, I didn't change the port on my Putty instance.

But the memory decrease still exists!

**Comment by JoaoLopesF** [comment]
HI,

I will see it.
Thanks for feedback.

Regards

Joao

**Comment by JoaoLopesF** [comment]
Hi,
I saw about Free heap on Arduino ESP8266 on the internet, as in: https://github.com/esp8266/Arduino/issues/1923.
Iggr, who brought the ESP8266 to the Arduino, said:
This memory should be reclaimed after a couple of minutes, ...

And this occurred in my tests like the sample Basic and occurs in seconds ....

Please check this, you can use the m command in telnet to display the memory

Regards

Joao

**Comment by bertmelis** [comment]
I didn't  know it would take minutes. Thanks for the comment!

I'll make a logger and see how it goes. Closing the issue for now.
